# -*- coding: utf-8 -*-
"""Cells_Annotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gZ-J1oakezIrtaEjG9c7UP4Z2myaQW-
"""

from PIL import Image
import numpy as np

annotation_file = {'File': [], 'Mask': [], 'Cell number': [], 'Class': []}
for colored_image, masks, file_name in zip(colored_images, all_masks[0], file_names):
  mask_name = masks
  masks = np.load(masks)
  colored_image = np.array(colored_image)
  colored_image = colored_image//65535 #65535 for 16-bit image, 255 for 8-bit image, etc.
  colored_image = colored_image.astype('float64')
  for mask_num in range(1, np.unique(masks).shape[0]):
    annotation_file['File'].append(file_name.split('\\')[1])
    annotation_file['Mask'].append(mask_name.split('\\')[1])
    annotation_file['Cell number'].append(mask_num)
    mask = np.ma.masked_values(masks, mask_num).mask
    masked_val = np.mean(image_thresh*mask)/np.mean(mask) # colored part of cell
    if masked_val==0:
        class_name = 0
    else:
        class_name = 1
    annotation_file['Class'].append(class_name)
