# -*- coding: utf-8 -*-
"""Get_mean_and_std.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1liBuMCFddchgdPRjdvOWMJTFkFIH4ILu
"""

from tqdm.notebook import tqdm
from torchvision import transforms

def get_mean_and_std(dataset):
    sum_channel = 0
    squared_sum_channel = 0
    n = len(dataset) * dataset[0].shape[0] * dataset[0].shape[1]
    for images in tqdm(dataset):
        # sum of values
        images = transforms.ToTensor(images)
        sum_channel += images.sum()
        # sum of squared values
        squared_sum_channel += images.pow(exponent=2).sum()
    mean = sum_channel / n  # E[x]
    std = (squared_sum_channel / n - mean**2).sqrt()  # E[x^2] - (E[X])^2
    return mean.numpy(), std.numpy()